import User from '../users/User';
import Main from '../Main';
import Debug from '../utils/Debug';

/**
 * Represents a verification method available to a user
 * Contains information about the method type, display details, and capabilities
 */
export interface VerificationMethod {
    /** The type of verification method (e.g., 'email', 'totp') */
    type: string;
    /** Human-readable name for the verification method */
    name: string;
    /** Detailed description of how the verification method works */
    description: string;
    /** Whether this verification method is currently enabled for the user */
    enabled: boolean;
    /** Whether codes can be sent via this method (false for TOTP, true for email) */
    can_send: boolean;
    /** Additional data needed to send verification codes (e.g., email address) */
    send_data?: {
        /** The target identifier for sending codes */
        target: number;
        /** Any additional fields required for sending codes via this method */
        [key: string]: any;
    };
}

/**
 * Configuration options for verification processes
 * Used to pass verification method information and session data
 */
export interface VerificationOptions {
    /** Array of available verification methods */
    methods: VerificationMethod[];
    /** Optional session identifier for tracking verification attempts */
    session_id?: string;
}

/**
 * Result object returned from verification attempts
 * Contains success status, descriptive message, and optionally the verified method
 */
export interface VerificationFactorResult {
    /** Whether the verification was successful */
    success: boolean;
    /** Descriptive message about the verification result */
    message: string;
    /** The verification method that was successfully used (optional) */
    verified_method?: string;
}

/**
 * Manager class for handling multi-factor authentication and verification
 * Provides methods for generating, sending, and verifying authentication codes
 * Supports multiple verification methods including TOTP (2FA) and email verification
 */
export default class VerificationFactorManager {
    /** Duration in minutes for verification code validity */
    private static readonly FACTOR_CODE_EXPIRY_MINUTES = 10;
    /** Length of generated verification codes */
    private static readonly FACTOR_CODE_LENGTH = 6;

    /**
     * Constructor for VerificationFactorManager
     * @param app - Main application instance providing access to services like database and email
     */
    constructor(private readonly app: Main) { }

    /**
     * Get available verification methods for a user
     * Returns an array of verification methods that are available for the given user,
     * including TOTP (2FA) if enabled and email verification if the user has a verified email
     * @param user - The user for whom to get available verification methods
     * @returns Array of VerificationMethod objects representing available verification options
     */
    getAvailableVerificationMethods(user: User): VerificationMethod[] {
        const methods: VerificationMethod[] = [];        // Add 2FA (TOTP) if enabled
        methods.push({
            type: 'totp',
            name: 'Authenticator App (2FA)',
            description: 'Use an authenticator app like Google Authenticator or Authy',
            enabled: user.twofa_enabled && !!user.twofa_secret,
            can_send: false // TOTP codes are generated by the authenticator app, not sent
        });

        // Add email verification if user has email
        methods.push({
            type: 'email',
            name: 'Email Verification',
            description: 'Receive a verification code via email',
            enabled: !!user.email && user.email_verified,
            can_send: true,
            send_data: {
                target: user.id
            }
        });

        return methods.filter(m => m.enabled);
    }

    /**
     * Check if additional verification is required for login
     * Returns true if the user has 2FA enabled or has a verified email address
     * This determines whether the login process should require additional verification steps
     * @param user - The user to check verification requirements for
     * @returns true if additional verification is required, false otherwise
     */
    isVerificationRequired(user: User): boolean {
        return user.twofa_enabled || !!user.email_verified;
    }

    /**
     * Generate a verification code for email-based verification
     * Creates a random 6-digit numeric code using secure random number generation
     * @returns A 6-digit string code for verification purposes
     */
    private generateFactorCode(): string {
        const digits = '0123456789';
        let code = '';

        for (let i = 0; i < VerificationFactorManager.FACTOR_CODE_LENGTH; i++) {
            const randomIndex = Math.floor(Math.random() * digits.length);
            code += digits[randomIndex];
        }

        return code;
    }

    /**
     * Create a verification factor code and store it in the database
     * Generates a new verification code, removes any existing codes for the user and method,
     * then stores the new code with an expiration time
     * @param user - The user for whom to create the verification code
     * @param method - The verification method type (currently only 'email' is supported)
     * @returns The generated code string, or null if an error occurred
     */
    async createFactorCode(user: User, method: 'email'): Promise<string | null> {
        try {
            const code = this.generateFactorCode();
            const expiresAt = new Date(Date.now() + VerificationFactorManager.FACTOR_CODE_EXPIRY_MINUTES * 60 * 1000);

            await this.app.database.verificationFactor.deleteMany({
                where: {
                    user_id: user.id,
                    method: method
                }
            });

            await this.app.database.verificationFactor.create({
                data: {
                    user_id: user.id,
                    method: method,
                    code: code,
                    expires_at: expiresAt
                }
            });

            return code;
        } catch (error) {
            Debug.error('Error creating factor verification code:', error);
            return null;
        }
    }

    /**
     * Send a verification code to the user via the specified method
     * Currently supports sending codes via email. The code should be generated
     * and stored before calling this method.
     * @param user - The user to send the verification code to
     * @param method - The method to use for sending ('email' is currently supported)
     * @returns true if the code was sent successfully, false otherwise
     */
    async sendVerificationCode(user: User, method: string): Promise<boolean> {
        if (method === 'email')
            return await this.app.emails.sendEmailVerificationCode(user);
        return false;
    }

    /**
     * Verify a factor code against all available verification methods for a user
     * Attempts to verify the provided code using each available verification method
     * until one succeeds or all methods have been tried
     * @param user - The user attempting verification
     * @param code - The verification code to validate
     * @returns VerificationFactorResult indicating success/failure and any relevant message
     */
    async verifyFactorCode(user: User, code: string): Promise<VerificationFactorResult> {
        var availableMethods = this.getAvailableVerificationMethods(user);
        if (!availableMethods.length)
            return {
                success: false,
                message: 'No verification methods available for this user'
            };

        for (const method of availableMethods) {
            const result = await this.verifyFactorMethodCode(user, code, method);
            if (result.success) {
                return {
                    success: true,
                    message: 'Verification code verified successfully',
                    verified_method: result.verified_method
                };
            }
        }

        return {
            success: false,
            message: 'Invalid verification code'
        };
    }

    /**
     * Verify a factor code using a specific verification method
     * Delegates the verification to the appropriate service based on the method type
     * @param user - The user attempting verification
     * @param code - The verification code to validate
     * @param method - The specific verification method to use
     * @returns VerificationFactorResult with success status, message, and verified method type
     */
    async verifyFactorMethodCode(user: User, code: string, method: VerificationMethod): Promise<VerificationFactorResult> {
        if (method.type === 'email')
            return await this.app.emails.verification.verifyFactorEmailCode(user, code);
        if (method.type === 'totp')
            return await this.app.totp.verifyFactorTOTPCode(user, code);
        return {
            success: false,
            message: `Unsupported verification method: ${method.type}`,
            verified_method: method.type
        };
    }

}


